/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadCodebaseRouteImport } from './routes/api/download-codebase'
import { Route as VSlugRouteImport } from './routes/v/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadCodebaseRoute = ApiDownloadCodebaseRouteImport.update({
  id: '/api/download-codebase',
  path: '/api/download-codebase',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/download-codebase': typeof ApiDownloadCodebaseRoute
  '/v/$slug': typeof VSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/download-codebase': typeof ApiDownloadCodebaseRoute
  '/v/$slug': typeof VSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/download-codebase': typeof ApiDownloadCodebaseRoute
  '/v/$slug': typeof VSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/download-codebase' | '/v/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/download-codebase' | '/v/$slug'
  id: '__root__' | '/' | '/api/download-codebase' | '/v/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDownloadCodebaseRoute: typeof ApiDownloadCodebaseRoute
  VSlugRoute: typeof VSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-codebase': {
      id: '/api/download-codebase'
      path: '/api/download-codebase'
      fullPath: '/api/download-codebase'
      preLoaderRoute: typeof ApiDownloadCodebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDownloadCodebaseRoute: ApiDownloadCodebaseRoute,
  VSlugRoute: VSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
